# Generated by Django 4.2.30 on 2026-08-11 08:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('vin', models.CharField(help_text='Unique VIN Code', max_length=17, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Vehicle title / name', max_length=100)),
                ('make', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('year', models.PositiveIntegerField()),
                ('color', models.CharField(max_length=30)),
                ('mileage', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('PURCHASED', 'Satyn alyndy'), ('IN_TRANSIT', 'Ýolda'), ('ARRIVED_TKM', 'Türkmenistana geldi'), ('SOLD', 'Satyldy')], default='PURCHASED', max_length=30)),
                ('location', models.CharField(choices=[('USA_COPART', 'Amerika (Copart)'), ('SHIPPING_TRANSIT', 'Ýük daşama ýola çykaryldy'), ('GEORGIA', 'Gruziýa'), ('TURKMENISTAN_INTERNAL', 'Türkmenistan (Içerki ýerleri)')], default='USA_COPART', max_length=50)),
                ('is_handed_over', models.BooleanField(default=False, help_text='Indicates if handover process (e.g. in Georgia) has taken place')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_owner', models.ForeignKey(blank=True, help_text='Assigned owner/employee managing the vehicle', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_vehicles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleHistoryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=100)),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle_changes', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle_owner_histories', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_logs', to='vehicles.vehicle')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VehicleExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('description', models.TextField(blank=True, default='')),
                ('stage', models.CharField(blank=True, default='', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='vehicles.vehicle')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VehicleDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='vehicle_docs/%Y/%m/')),
                ('title', models.CharField(max_length=150)),
                ('document_type', models.CharField(choices=[('PHOTO', 'Surat (Photo)'), ('AUCTION_DOC', 'Auksion Resminamasy'), ('SHIPPING_DOC', 'Ýük daşama Resminamasy'), ('REPAIR_BILL', 'Ussa / Serhet çykdajysy'), ('OTHER', 'Başga')], default='PHOTO', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='vehicles.vehicle')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
