# Generated by Django 4.2.30 on 2026-10-06 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0003_vehicle_pending_handover_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='photo',
            field=models.ImageField(blank=True, help_text='Vehicle primary photo', null=True, upload_to='vehicles/%Y/%m/'),
        ),
    ]
